import pandas as pd
import numpy as np
from typing import Union
import pathlib


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = pathlib.Path(data_fname)
        self.data = None

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)
        # return(self.data)

    def show_age_distrib(self) -> tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
          Number of people in a given bin
        bins : np.ndarray
          Bin edges
        """
        # data = QuestionnaireAnalysis.read_data()
        _ = self.data.hist(column='age', bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
        hist, bin_edges = np.histogram(self.data.age, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
        # hist_tuple = (hist, bin_edges)
        return(hist, bin_edges)

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
          A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
          the (ordinal) index after a reset.
        """
        QuestionnaireAnalysis.read_data()
        # remove the folowing:
        data2 = self.data
        data2 = data2.drop(data2[data2.email.str.count("@") != 1].index)  # if it doesnt have exactly one "@"
        data2 = data2.drop(data2[data2.email.str.count(".") == 0].index)  # if it doesnt have any "."
        data2 = data2.drop(data2[data2.email.str.endswith("@")].index)  # if it ends with "@"
        data2 = data2.drop(data2[data2.email.str.endswith(".")].index)  # if it ends with "."
        data2 = data2.drop(data2[data2.email.str.startswith("@")].index)  # if it starts with "@"
        data2 = data2.drop(data2[data2.email.str.startswith(".")].index)  # if it starts with "."
        data2 = data2.drop(data2[data2.email.str.contains('@.', regex=False)].index)  # if "." comes right after "@"
        data2 = data2.drop(data2[~data2.email.str.endswith("com")].index)  # if it doesnt end with "com"
        return(data2)

    def fill_na_with_mean(self) -> tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
          The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
          Row indices of the students that their new grades were generated
        """

        # QuestionnaireAnalysis.read_data()
        arr = self.data.iloc[:, 7:12].isna().any(axis=1)
        arr = np.asarray(np.where(arr == True))

        data_tranposed = self.data.iloc[:, 7:12].T
        straight_data = data_tranposed.fillna(data_tranposed.mean(axis=0)).T
        self.data.iloc[:, 7:12] = straight_data

        return(self.data, arr)

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        
        score = np.mean(self.data.iloc[:, 7:12], axis=1)
        mor_than_max_nans = self.data.iloc[:, 7:12].isna().sum(axis=1) > maximal_nans_per_sub
        score.iloc[mor_than_max_nans] = np.nan
        score = score[~mor_than_max_nans].astype(np.uint8)

        pd.concat([self.data, score], axis=1)

        return(self.data)

    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """

        # QuestionnaireAnalysis.read_data()
        self.data['Index'] = self.data.index
        data = self.data.set_index(['Index', 'gender', 'age'])

        new_age = pd.Series(np.where(data.age < 40, 'smaller_than_40', 'greater_than_40'), name="new_age", index=data.index)
        data_with_new_age = pd.concat([data, new_age], axis=1)

        grouped = data_with_new_age.groupby(["gender", "new_age"]).mean()
        grouped = grouped[["q1", "q2", "q3", "q4", "q5"]]

        return(grouped)
