import pandas as pd
from pathlib import *
import json
import numpy as np
import matplotlib.pyplot as plt


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname):
        
        self.data_fname = Path(data_fname)
        self.data = self.read_data()

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        
        data= pd.read_json(self.data_fname)
        return data

#     1. Plot the distribution of ages of the participants. The bins for the histogram should be
#  [0, 10), [10, 20), [20, 30), ..., [90, 100]. The function should return the result.

#    ```python
    def show_age_distrib(self):

      """Calculates and plots the age distribution of the participants.
      Returns
      -------
      hist : np.ndarray
      Number of people in a given bin
      bins : np.ndarray
      Bin edges
      """
        bins = np.arange(0,110,10)
        hist = np.histogram(self.data['age'], bins= bins)
        plt.hist(self.data['age'], bins= bins)  # arguments are passed to np.histogram
        plt.title("Histogram for paticipant age")
        plt.show()
        return bins, hist

        
    # age_hist = self.data.hist(column='age', bins= bins)

a= QuestionnaireAnalysis('data.json')