import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Union, Tuple
import json

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[Path, str]):
        if type(data_fname) == str:
            self.data_fname = Path.cwd().joinpath(data_fname)
        else:
            self.data_fname = data_fname

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        list_of_dict = json.loads(self.data_fname.read_text())
        self.data = pd.DataFrame(list_of_dict).set_index("id")
        self.data = self.data.replace("nan", np.NaN)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
        Number of people in a given bin
        bins : np.ndarray
        Bin edges
        """    
        ages = self.data["age"]#.replace("nan", 0).to_numpy()
        bins = np.asarray([(x,x+10) for x in range(0,100,10)])
        count = []
        bin_names = []

        for values in bins:
            count.append(np.count_nonzero((ages>values[0])&(ages<values[1])))
        hist = np.array(count)

        for combo in bins:
            bin_names.append(str(combo[0])+'-'+str(combo[1]))
        plt.bar(bin_names,hist)
        plt.show()
        
        return hist, bins

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
        A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
        the (ordinal) index after a reset.
        """
        def conditions_for_mail(email: str):
            if (email.count("@") != 1) | (email.find("@") == 0) | (email.find("@") == len(email)-1):
                return False
            elif (email.count(".") == 0) | (email.find(".") == 0)| (email.rfind(".") == len(email)-1):
                return False
            elif (email[email.find("@") + 1] == "."):
                return False
            else:
                return True

        new_df = self.data[[(conditions_for_mail(x) == True) for x in self.data.email.values.tolist()]]
        new_df.reset_index(drop=True)

        return new_df

        

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
        The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
            Row indices of the students that their new grades were generated
        """

        question_df = self.data.loc[:,"q1":"q5"]
        arr = np.array(question_df.isna().any(axis=1).index)
        new_question_df = question_df.apply(lambda row: row.fillna(row.mean()), axis=1)
        new_df = self.data.copy()
        new_df.loc[:,"q1":"q5"] = new_question_df

        return new_df , arr
    
    if __name__ == '__main__' :
        read_data()
        remove_rows_without_mail()
        fill_na_with_mean()

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """

        

    
